"""Initial revision

Revision ID: 541a9da4ad35
Revises: 5d81d41778b1
Create Date: 2026-05-06 01:07:02.740141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541a9da4ad35'
down_revision: Union[str, Sequence[str], None] = '5d81d41778b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('SKU', sa.String(), nullable=False),
    sa.Column('shop_domain', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SKU', 'shop_domain', name='sku_shop_domain'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_products_SKU'), 'finance', ['SKU'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'finance', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'finance', ['category'], unique=False)
    op.create_index(op.f('ix_products_shop_domain'), 'finance', ['shop_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_shop_domain'), table_name='finance')
    op.drop_index(op.f('ix_products_category'), table_name='finance')
    op.drop_index(op.f('ix_products_brand'), table_name='finance')
    op.drop_index(op.f('ix_products_SKU'), table_name='finance')
    op.drop_table('finance')
    # ### end Alembic commands ###
